# Generated by Django 2.1.7 on 2019-04-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20190408_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
    ]
